name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm install
    
    - name: Start development server
      run: |
        npm run dev &
        echo $! > server.pid
      continue-on-error: true

    - name: Run Playwright tests
      run: |
        npm test
      env:
        BASE_URL: 'http://localhost:5173'
    
    - name: Stop development server
      run: |
        kill $(cat server.pid) || true
      continue-on-error: true
