name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  dev-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run development server
      run: npm run dev &
      continue-on-error: true

  e2e-tests:
    runs-on: ubuntu-latest
    needs: dev-server
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
