name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff2-encoder1 \
          libvpx6 \
          libevent-2.1-7 \
          libopus0 \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          libharfbuzz0b \
          libhyphen0 \
          libmanette-0.2-0 \
          libflite1 \
          libgles2-mesa \
          libx264-160

    - name: Install dependencies
      run: npm install
    
    - name: Install Playwright browsers
      run: npx playwright install
    
    - name: Start development server
      run: |
        npm run dev &
        echo $! > server.pid
      continue-on-error: true

    - name: Run Playwright tests
      run: |
        npm test
      env:
        BASE_URL: 'http://localhost:5173'
    
    - name: Stop development server
      run: |
        kill $(cat server.pid) || true
      continue-on-error: true