name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint-ci
        continue-on-error: true # Continue even if linting fails to upload the report

      - name: Upload lint results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: ./test-results/ci-lint-results.html

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npm test

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-reports
          path: |
            test-results/index.html
            test-results/e2e-test-results.json
