name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  dev-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start development server
      run: |
        npm run dev &
        echo $! > server.pid
      continue-on-error: true

  e2e-tests:
    runs-on: ubuntu-latest
    needs: dev-server
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Wait for server to be ready
      run: sleep 30  # Adjust the wait time as needed

    - name: Run E2E tests
      run: npm test

    - name: Stop development server
      run: |
        kill $(cat server.pid) || true
      continue-on-error: true
