name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: |
        npx playwright install chromium
        npx playwright install firefox
        npx playwright install msedge

    - name: Run Playwright tests
      run: npm test
